set(VIAL_ENABLE ON CACHE BOOL "KB" FORCE)
set(VIA_ENABLE ON CACHE BOOL "KB" FORCE)
set(VIAL_INSECURE ON CACHE BOOL "KB" FORCE)

set(BOOTMAGIC_ENABLE ON CACHE BOOL "KB" FORCE)
set(MOUSEKEY_ENABLE ON CACHE BOOL "KB" FORCE)
set(EXTRAKEY_ENABLE ON CACHE BOOL "KB" FORCE)
set(COMMAND_ENABLE ON CACHE BOOL "KB" FORCE)
set(EEPROM_DRIVER "wear_leveling" CACHE STRING "KB" FORCE)
set(USB_ENABLE ON CACHE BOOL "KB" FORCE)
set(GRAVE_ESC_ENABLE ON CACHE BOOL "KB" FORCE)

set(BOOTLOADER_TYPE "uf2" CACHE STRING "KB" FORCE)

