
# CONFIG_CLOCK_CONTROL_NRF=y
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# CONFIG_ZMK_BLE=y
# CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
CONFIG_I2C=n
# CONFIG_USB_DEVICE_SUSPEND=n
# CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_LOG_MAX_LEVEL=3
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_ZMK_RTT_LOGGING=n
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ZMK_LOG_LEVEL_DBG=n
CONFIG_PM_DEVICE=y
CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_LOG_MODE_DEFERRED=y
# CONFIG_USB_DEVICE_LOG_LEVEL_INF=n

CONFIG_COMPILER_OPT="-Os"
CONFIG_LTO=y

# Enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=n

CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=4
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=4
# CONFIG_USB_DEVICE_SN="vial:f64c2b3c"
CONFIG_SERIAL=y
# CONFIG_USE_DT_CODE_PARTITION=y
# CONFIG_BUILD_OUTPUT_UF2=y

CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=n
# CONFIG_LOG_TIMESTAMP_64BIT=n
# CONFIG_ZMK_BLE=y
# CONFIG_ZMK_USB=y


# BLE 广播名
CONFIG_BT_DEVICE_NAME="WCorne-BLE"

# USB 设备名s
CONFIG_USB_DEVICE_PRODUCT="W-Corne"
CONFIG_ZMK_BLE=y
# CONFIG_PERIPHERAL_QF=y
# CONFIG_ZMK_SPLIT=y
# CONFIG_ZMK_SPLIT_BLE=y

CONFIG_EEPROM_WEAR_LEVELING=y
CONFIG_USB_HID_DEVICE_COUNT=2
CONFIG_BT_ID_MAX=4
CONFIG_BT_MAX_CONN=6