
# CONFIG_LOG_MAX_LEVEL=3
# CONFIG_LOG_MODE_MINIMAL=n
CONFIG_ZMK_RTT_LOGGING=n
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_ZMK_LOG_LEVEL_DBG=n
CONFIG_PM_DEVICE=y
CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_LOG_MODE_DEFERRED=y

CONFIG_USB_DEVICE_PRODUCT="P16-R"
CONFIG_BT_DEVICE_NAME="P16-BLE1"
CONFIG_EEPROM_WEAR_LEVELING=y
CONFIG_USB_HID_DEVICE_COUNT=2


CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=n