
CONFIG_SPI=y
CONFIG_SPI_NRFX=y
CONFIG_LOG_MAX_LEVEL=3
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_ZMK_RTT_LOGGING=n
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=0

CONFIG_ZMK_LOG_LEVEL_DBG=n
CONFIG_PM_DEVICE=y
CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_LOG_MODE_DEFERRED=y


CONFIG_BT_DEVICE_NAME="Pad17Air-BLE"
CONFIG_USB_DEVICE_PRODUCT="Pad17Air-ZMK"
CONFIG_EEPROM_WEAR_LEVELING=y
CONFIG_USB_HID_DEVICE_COUNT=2

# CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1 

# CONFIG_ZMK_QF_595=y
CONFIG_BT_ID_MAX=4
CONFIG_BT_MAX_CONN=6

CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW=y


# 开机自动开启
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1
# 空闲自动关闭(推荐省电)
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=50

CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_LED_STRIP=y
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y

CONFIG_ZMK_BEHAVIOR_METADATA=n

# 添加ZMK Studio支持
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 蓝牙连接安全设置取消
CONFIG_BT_SMP_ENFORCE_MITM=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_BT_CTLR_PHY_2M=n





# CONFIG_SHELL=n
# CONFIG_CONSOLE=n
# CONFIG_UART_CONSOLE=n

# 强制 GCC 以尺寸优先优化
# CONFIG_COMPILER_OPTIMIZATION_SIZE=y
# 顺带关掉调试信息
# CONFIG_DEBUG_OPTIMIZATIONS=n
# CONFIG_NO_OPTIMIZATIONS=n
# CONFIG_BOOT_BANNER=n
# CONFIG_SENSOR=n
